name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: csexton/debugger-action@master
      name: debugger
      timeout-minutes: 360
      continue-on-error: true
